include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat these issues as warnings.
    deprecated_member_use: warning
    avoid_print: warning
    use_build_context_synchronously: warning
    unused_import: warning
    unnecessary_import: warning

linter:
  rules:
    # Add any specific rules you want to enforce or disable.
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true